### ISSUE TITLE
网页样式跟原网页的混了

### ISSUE THREAD

**Issue by kagari2613** [nickyc975/EdgeTranslate#1]

**Comment by nickyc975** [comment]
能不能提供网页链接？

**Comment by kagari2613** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        div{
            width: 100px;
            height: auto;
            border: red solid 1px;
            float: left;
            word-wrap: break-word;
            margin-right: 10px;
        }

    </style>
</head>
<body>


    <div class="item1">
        hjsdjfdhsjfjdfhowueuioqw3uoyhqwhshdfbjhkjsdfjkasejjksefdukj就会回到房间很干净的软件划归为 已经和维护个人就会俄日

    </div>
    <div class="item2">
        和技术丢华为u后额合同发给尽可能变为搜哦图文瑞和iu同样哟喂然后我角色放开怀抱问题u哦i我和瑞回归vi捷克人
    </div>

</body>
</html>`
就这样，复制到本地自己建一个html就可以了。临时写的，现在我准备试试，你翻译却网络错误了，不过你插件的提示翻译还是应用了这个页面的边框。

**Comment by kagari2613** [comment]
你在body下面插了一个div

Nicky Chen <notifications@github.com> 于 2018年8月7日周二 16:12写道：

**Comment by Mark-Fritz** [comment]
感谢反馈，我们会尽快修复

**Comment by nickyc975** [comment]
此问题已修复，将在下个版本生效。
