### ISSUE TITLE
与SwitchyOmega插件共用，无法连接网络翻译失败。

### ISSUE THREAD

**Issue by Halfcoffee** [nickyc975/EdgeTranslate#2]
在使用 SwitchyOmega 插件时，设置会影响到 侧边翻译 的使用，导致无法连接服务器。
烦请更新，解决这个问题。
谢谢！

**Comment by nickyc975** [comment]
能不能描述的更详细一点？因为我也在使用SwitchyOmega，但并没有遇到这个问题。

**Comment by Halfcoffee** [comment]
嗯，因为我用的是局域网pac代理，局域网的其它电脑当作出口机器。

**Comment by Halfcoffee** [comment]
@nickyc975 难道是我代理的原因，我检查了一下，我其它应用和插件都是正常的啊，例如：谷歌翻译

**Comment by nickyc975** [comment]
@Halfcoffee 你去插件管理页面打开开发者模式，然后点击侧边翻译的背景页和SwitchyOmega的背景页看看报错

**Comment by Halfcoffee** [comment]
![Uploading image.png…]()

**Comment by Halfcoffee** [comment]
@nickyc975 侧边翻译显示 背景页 无效，没有任何错误。

**Comment by Halfcoffee** [comment]
@nickyc975 SwitchyOmega的是以下这些，看起来也算不上错误把。
Options << Options#applyProfile 
Array(1)
0
:
"system"
length
:
1
__proto__
:
Array(0)
background.js:27 Options << Options#updateProfile 
Array(1)
0
:
["system"]
length
:
1
__proto__
:
Array(0)
background.js:27 Options << Options#updateProfile 
Array(0)
length
:
0
__proto__
:
Array(0)
background.js:27 external proxy:  
Object
background.js:27 Options << Options#applyProfile 
Array(2)
0
:
"system"
1
:
{proxy: false, system: true, reason: "external"}
length
:
2
__proto__
:
Array(0)

**Comment by Halfcoffee** [comment]
@nickyc975 chrome版本 68.0.3440.106（正式版本） （64 位）

**Comment by Halfcoffee** [comment]
@nickyc975 关闭代理就正常，使用系统代理，就是网络连接失败。
但是使用代理，访问其它网站什么的都是正常的。

**Comment by nickyc975** [comment]
你试试使用代理的情况下直接访问这个网址正常吗：https://translate.google.cn

**Comment by Halfcoffee** [comment]
@nickyc975 cn不行，com可以。

**Comment by nickyc975** [comment]
那应该是你代理的问题，我们为了保证插件在国内能正常使用，用的是https://translate.google.cn

**Comment by Halfcoffee** [comment]
@nickyc975 好的。
