### ISSUE TITLE
页面是多个iframe问题

### ISSUE THREAD

**Issue by viewhang** [nickyc975/EdgeTranslate#4]
当页面是多个iframe的时候，点击翻译会在每个每个iframe里生成一个翻译界面。而且弄成侧边生成iframe的方式会影响页面的布局，尤其是页面带响应式的时候，体验不太好。建议改成侧边弹窗。

**Comment by Mark-Fritz** [comment]
可以给一个出问题的网站示例吗

**Comment by viewhang** [comment]
随便一个带iframe的网页都会出现，比如[这个](http://www.runoob.com/try/try.php?filename=tryhtml_iframe)，带响应式的页面会变，比如[这个](http://www.w3school.com.cn/demo/demo_rwd_bootstrap.html)

**Comment by nickyc975** [comment]
响应式布局那个可能跟屏幕长宽比有关，我这边测试没发现问题。iframe的问题我们基本找到原因了，正在解决。

**Comment by nickyc975** [comment]
另外使用侧边弹窗的话会遮挡内容，影响阅读体验。
