### ISSUE TITLE
固定侧边后查词过程中动画重复出现

### ISSUE THREAD

**Issue by chenxilong** [nickyc975/EdgeTranslate#5]
**Describe the bug**
选择固定侧栏后，每次查词都会有侧栏滑出的动画

 Browser chrome
 Version 69

**Comment by nickyc975** [comment]
这不是bug，我们做成这样是为了提醒用户翻译结果已经更新了。

**Comment by ImMrMa** [comment]
反复出现真的太难受了，其实还是谷歌原生那个更合理一些

**Comment by nickyc975** [comment]
这个问题我们下个版本会改，只是目前没时间，预计中秋之后能解决。

**Comment by ImMrMa** [comment]
我看在谷歌里，正常的pdf打开，直接选择其中的文字，放在剪贴板里也是很正确的文字，为什么一定要把它转成html呢，转成html反而得到的文字有的时候会出现错误，你们不能直接获取pdf里头选中的字符吗，我也很好奇这个，不好意思我没有做过开发，只是觉得这个功能可以这么改。我很期待一个比谷歌强大，好用的翻译工具。

**Comment by nickyc975** [comment]
这个是因为谷歌浏览器自带的那个pdf阅读器不支持划词翻译，只能通过复制单词到输入框里进行翻译，所以我们用了另外一个pdf阅读器替换了它，如果你不喜欢的话可以在设置里关掉这个功能。

**Comment by ImMrMa** [comment]
那可以这样吗，把框固定住，然后检测剪贴板信息，发生变化，就翻译，我更喜欢原声的pdf浏览器一些。不然每次都复制贴贴到你们的框里，很麻烦。按照我的方法，就只需要crtl+c一下，就能翻译，也不会很麻烦，我是很期待这个功能。。。。。。

**Comment by nickyc975** [comment]
其实还有右键翻译的功能的，我忘了告诉你了。

在原生的pdf阅读器里，选中单词之后点鼠标右键，在展开的菜单里选择“翻译 ‘xxx’”就可以了。

**Comment by nickyc975** [comment]
这个功能是在任何页面都可以用的。

**Comment by ImMrMa** [comment]
右键是二级菜单，很难受啊

**Comment by nickyc975** [comment]
什么二级菜单？

**Comment by ImMrMa** [comment]
就是说，我每次想翻译一个单词，都得右击，然后找到选项，翻译，然后再关掉弹出的对话框，很慢，很麻烦

**Comment by ImMrMa** [comment]
一篇pdf论文翻译100个单词，就需要400个操作，这不高效了，如果你们可以直接固定一个框，复制贴贴一次显示一下结果，就只需要勾选不认识的单词，也不用鼠标动来动去，省了很多操作。

**Comment by Mark-Fritz** [comment]
你说的固定一个框是哪个框  ，可以描述下吗

**Comment by ImMrMa** [comment]
我是说能不能在原生的pdf界面固定一个框出来，然后我每次检测我的剪贴板的内容，当发现不一样时，就翻译出来，显示在框里，这样我就和在正常网页上划词翻译是一样的效果，也很高效。

**Comment by nickyc975** [comment]
对了，如果你觉得选词准确性低的话可以试试双击选词，只要是不是在行首和行尾一般不会出错

**Comment by ImMrMa** [comment]
好的

**Comment by ImMrMa** [comment]
对的，我刚才说的就是不知道能不能在原生的pdf上实现这个功能

**Comment by Mark-Fritz** [comment]
> 我是说能不能在原生的pdf界面固定一个框出来，然后我每次检测我的剪贴板的内容，当发现不一样时，就翻译出来，显示在框里，这样我就和在正常网页上划词翻译是一样的效果，也很高效。

如果想要固定一个框框的话，就在弹出的侧边栏里点击 固定 的那个按钮，这个框框就会一直固定住
然后用pdf阅读器，在设置里面打开选中即翻译的功能，你体验一下是不是你想表达的需求

**Comment by nickyc975** [comment]
在原生的pdf阅读器上是没办法实现双击选词直接翻译和划词翻译的，这也是为什么我们用了现在这个pdf阅读器。原生的那个太简陋了。

**Comment by ImMrMa** [comment]
直接crtl+c获取内容，这样你们把框固定出来，我这边选中crtl+c，然后框里检测到剪贴板的内容就自动翻译，也可以把这样使用原生的pdf

**Comment by Mark-Fritz** [comment]
> 直接crtl+c获取内容，这样你们把框固定出来，我这边选中crtl+c，然后框里检测到剪贴板的内容就自动翻译，也可以把这样使用原生的pdf

我觉得框固定还是用户自己来固定的好， 我们总不能每加载一个页面就固定一个框吧

**Comment by ImMrMa** [comment]
我觉得咱俩没有沟通好，但我真的又挺喜欢这个项目的，你们要是有兴趣，加微信聊聊吧，我的微信870587394

**Comment by nickyc975** [comment]
大多数情况下双击选词的准确性是高于手动划词的，所以其实在扩展自带的pdf阅读器里使用双击选词应该是最便捷的方案，这个你可以自己体验对比。

另外如果采用ctrl+c的方式的话会增加不少工作量，我们目前没有太多时间做，还有不少更重要的功能要做呢。

**Comment by ImMrMa** [comment]
好吧。。。你们努力吧，不喜欢那个扩展浏览器，单选真的难受
