### ISSUE TITLE
侧边能不能放在左边，或者悬浮式的，我很不习惯右边这个方式，你们的软件速度很快，很不错，界面也很好，就是右侧边很难受

### ISSUE THREAD

**Issue by ImMrMa** [nickyc975/EdgeTranslate#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickyc975** [comment]
收到，我们会考虑在下个版本中增加设置侧边弹出位置的功能。

**Comment by ImMrMa** [comment]
那真是太棒了，其实，你们应该固定在前端后就不要动画了，我每次翻译一次动画都出来一次，很烦。其实谷歌原生的那个插件是很好的，我这不知道为什么接口总是抽风~~，希望多整几个翻译接口，或者用谷歌国内那个接口吧

**Comment by Mark-Fritz** [comment]
> 那真是太棒了，其实，你们应该固定在前端后就不要动画了，我每次翻译一次动画都出来一次，很烦。其实谷歌原生的那个插件是很好的，我这不知道为什么接口总是抽风~~，希望多整几个翻译接口，或者用谷歌国内那个接口吧
> […](#)
> 在 2018年9月14日，下午5:03，Nicky Chen ***@***.***> 写道： 收到，我们会考虑在下个版本中增加设置侧边弹出位置的功能。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

现在用的就是国内的接口，可以描述一下怎么抽风的吗
动画总是出现我们是故意设置的，用于提醒用户翻译结果以及更新，我们再考虑考虑要不要把这个动画去掉，之前也有小伙伴反映过这个问题

**Comment by ImMrMa** [comment]
就是莫名奇妙，什么翻译也出不来，提示借口网络不通，弹出那个提示框，一般谷歌翻译插件不能用(翻译网站能进去)你们的翻译也会出现相同的情况，不知道为什么
