### ISSUE TITLE
The icon is hidden automatically when clicking "翻译"

### ISSUE THREAD

**Issue by DuJunda** [nickyc975/EdgeTranslate#8]
**描述问题**

无论是在pdf中，还是在网页中，点击图标，输入文字之后，点击翻译，虽然会出现翻译的结果，但是图标会自己隐藏起来

**出现问题的网址**

所有

**复现步骤**

已给出

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

chrome

版本 69.0.3497.92（正式版本） （64 位）

1.3.0

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fritz** [comment]
是输入框自动隐藏起来了吗

**Comment by 1160300522** [comment]
yes，就像我给你发的截图那样。不过不打开文件访问权限，是无翻译结果+隐藏，打开之后是有翻译结果+隐藏
