### ISSUE TITLE
中国国内环境下无法进行翻译，是否有除了谷歌外的其他的翻译方式或者网络方面的解决方式呢

### ISSUE THREAD

**Issue by XuXianTao** [nickyc975/EdgeTranslate#9]
**描述问题**

国内环境下无法使用谷歌翻译服务，相应的扩展也无效了。划词后一直处于读取状态

**问题截图**

![image](https://user-images.githubusercontent.com/32198066/47952826-577f5180-dfb0-11e8-86fe-c48b60a4d1ec.png)

**使用环境**

chrome
版本 68.0.3440.84（正式版本） （64 位）

_插件版本 1.3.0

**Comment by Mark-Fritz** [comment]
你试着访问以下这个网址
https://translate.google.cn/#en/zh-CN/test
如果这个打不开,应该是你网络可能存在问题
如果这个网址可以正常访问,但是扩展不能使用的话,我们就找找扩展自己的bug

**Comment by XuXianTao** [comment]
> 你试着访问以下这个网址
> https://translate.google.cn/#en/zh-CN/test
> 如果这个打不开,应该是你网络可能存在问题
> 如果这个网址可以正常访问,但是扩展不能使用的话,我们就找找扩展自己的bug

![image](https://user-images.githubusercontent.com/32198066/47954434-0fb6f500-dfc5-11e8-88d9-f2e19fdcf68c.png)

似乎是访问不了。看来是国内网络的问题了。还是只能找方式科学上网了，谢谢了～

**Comment by Mark-Fritz** [comment]
试着用浏览器访问一下那个网址看看,
这个网址就是我们使用的api接口 ,直接使用国内网络就可以访问的,不需要翻墙的
如果你还是不能访问的话,试着检查一下自己的代理设置或者防火墙设置,是否将这个网址屏蔽了
应该是自己本地网络的问题

**Comment by XuXianTao** [comment]
> 试着用浏览器访问一下那个网址看看,
> 这个网址就是我们使用的api接口 ,直接使用国内网络就可以访问的,不需要翻墙的
> 如果你还是不能访问的话,试着检查一下自己的代理设置或者防火墙设置,是否将这个网址屏蔽了
> 应该是自己本地网络的问题

看来是本地环境的问题了。
手机用流量可以正常访问，不过电脑因为是校园网环境，估计是学校的网络配置问题了，这个就没什么办法了。总之还是谢啦～

**Comment by Mark-Fritz** [comment]
好的

> > 试着用浏览器访问一下那个网址看看,
> > 这个网址就是我们使用的api接口 ,直接使用国内网络就可以访问的,不需要翻墙的
> > 如果你还是不能访问的话,试着检查一下自己的代理设置或者防火墙设置,是否将这个网址屏蔽了
> > 应该是自己本地网络的问题
> 
> 看来是本地环境的问题了。
> 手机用流量可以正常访问，不过电脑因为是校园网环境，估计是学校的网络配置问题了，这个就没什么办法了。总之还是谢啦～

好的
